# คำสั่งรับข้อความ ใช่ฟังก์ชัน input()
# ***** ตัวแปร variable คือ ขื่อที่ dev ตั้งขึ้นมาเอง (เป็นไปตามกฏการตั้งชื่อ)
#ฟังก์ชันที่ใช้แสดงแปลงข้อความเป็นตัวเลข ใช้ฟังก์ชัน int(), float()

fullname = input("ป้อนขื่อ: ")
mid_sroce = input('ป้อนคะแนนกลางภาค:')
final_sroce = input('ป้อนคะแนนปลายภาค:')
quiz_sroce = input('ป้อนคะแแนนเก็บ:')
print('-----------------')
print(f'สวัสดีคุณ : {fullname}')
print(f'คณสอบได้คะแนนรวม : {int(mid_sroce) + int(final_sroce) + int(quiz_sroce)} คะแนน')
print('-----------------')